import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";


const monserrat = Montserrat({
  variable: "--font-monserrat",
  subsets: ["latin"],
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Core Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${monserrat.className} h-full antialiased`}>
      <body className="min-h-ful flex flex-col  min-h-screen bg-zinc-950 text-zinc-100">
            {children}
            <Toaster position="top-right" richColors /> 
      </body>
    </html>
  );
}
